"""
generate_manifest.py — Lightweight manifest generator for CODESYS XML export snapshots.

Usage:
    python scripts/generate_manifest.py <export_dir> [--project-name <name>] [--project-version <ver>]

Example:
    python scripts/generate_manifest.py exports/v1 --project-name "apollo-3cs-0.004bf - eolus- v5" --project-version "1.0.0.0"

This script scans the xml/ subdirectory of the given export directory, computes file sizes,
and writes a MANIFEST.json with metadata about the snapshot.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone


def scan_xml_files(xml_dir):
    """Scan xml_dir for .xml files and return a list of file info dicts."""
    files = []
    if not os.path.isdir(xml_dir):
        return files
    for fname in sorted(os.listdir(xml_dir)):
        if fname.lower().endswith(".xml"):
            fpath = os.path.join(xml_dir, fname)
            size_kb = round(os.path.getsize(fpath) / 1024.0, 1)
            files.append({
                "filename": fname,
                "size_kb": size_kb,
            })
    return files


def guess_role(filename):
    """Best-effort role assignment based on filename patterns."""
    name_lower = filename.lower()
    if "apollo-3cs" in name_lower or "project" in name_lower:
        return "main-project"
    if "primary" in name_lower:
        return "core-library"
    if "services" in name_lower:
        return "services-library"
    if "apollo" in name_lower:
        return "extension-library"
    if "canplc" in name_lower or "can" in name_lower:
        return "can-library"
    if "device" in name_lower:
        return "device-config"
    if "machine" in name_lower:
        return "machine-library"
    if "common" in name_lower:
        return "common-library"
    if "build" in name_lower:
        return "build-config"
    return "unknown"


def build_manifest(xml_files, project_name, project_version):
    """Build the MANIFEST.json structure."""
    total_kb = round(sum(f["size_kb"] for f in xml_files), 1)

    # Add role and description to each file
    role_descriptions = {
        "main-project": "Main project program",
        "core-library": "Core system library",
        "services-library": "Network services, TCP servers/clients, reporting",
        "extension-library": "Apollo crane-specific extensions",
        "can-library": "CAN/PLC communication library",
        "device-config": "ESX-3CS device configuration",
        "machine-library": "Machine-specific types",
        "common-library": "Common types and utilities",
        "build-config": "Build configuration",
        "unknown": "Unrecognized file",
    }

    for f in xml_files:
        role = guess_role(f["filename"])
        f["role"] = role
        f["description"] = role_descriptions.get(role, "Unrecognized file")

    # Derive export_id from the parent directory name
    export_id = "unknown"

    manifest = {
        "export_id": export_id,
        "created": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "project": {
            "name": project_name,
            "version": project_version,
            "target": "STW ESX-3CS",
            "codesys_version": "V3.5 SP11",
            "profile": "STW CODESYS V3.5 SP11 - ESX-3CS",
        },
        "source": {
            "binary_project": "src/<project>.project",
            "export_method": "CODESYS IDE manual export (PLCopenXML)",
            "export_script_ref": "exported-src/export_plcopenxml.py",
        },
        "xml_files": xml_files,
        "total_xml_files": len(xml_files),
        "total_xml_size_kb": total_kb,
        "notes": [
            "Manifest generated by scripts/generate_manifest.py.",
            "Review and edit role/description fields as needed.",
            "Add compiler_defines and total_pou_count_approx manually if known.",
        ],
    }

    return manifest


def main():
    parser = argparse.ArgumentParser(
        description="Generate MANIFEST.json for a CODESYS XML export snapshot."
    )
    parser.add_argument(
        "export_dir",
        help="Path to the export directory (e.g., exports/v1)",
    )
    parser.add_argument(
        "--project-name",
        default="Unknown Project",
        help="Human-readable project name",
    )
    parser.add_argument(
        "--project-version",
        default="0.0.0.0",
        help="Project version string",
    )
    args = parser.parse_args()

    export_dir = os.path.normpath(args.export_dir)
    xml_dir = os.path.join(export_dir, "xml")

    if not os.path.isdir(export_dir):
        print("ERROR: Export directory not found: %s" % export_dir, file=sys.stderr)
        sys.exit(1)

    xml_files = scan_xml_files(xml_dir)
    if not xml_files:
        print("WARNING: No .xml files found in %s" % xml_dir, file=sys.stderr)

    manifest = build_manifest(xml_files, args.project_name, args.project_version)

    # Derive export_id from directory name
    dir_name = os.path.basename(export_dir)
    manifest["export_id"] = dir_name

    output_path = os.path.join(export_dir, "MANIFEST.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print("Manifest written to: %s" % output_path)
    print("  Export ID: %s" % manifest["export_id"])
    print("  XML files: %d" % manifest["total_xml_files"])
    print("  Total size: %.1f KB" % manifest["total_xml_size_kb"])


if __name__ == "__main__":
    main()
